[package]
name = "ble_lights"
version = "0.1.0"
authors = ["Mikołaj Chwalisz <m.chwalisz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumble = "0.3.0"
